import { TourPackage, Destination, Service, Testimonial } from "@/types";

export const packages: TourPackage[] = [
  {
    id: "1",
    slug: "cultural-triangle-explorer",
    title: "Cultural Triangle Explorer",
    shortDescription: "Discover ancient kingdoms, sacred temples, and UNESCO World Heritage sites.",
    description:
      "Immerse yourself in Sri Lanka's rich history as you explore the ancient cities of Anuradhapura and Polonnaruwa, climb the legendary Sigiriya Rock Fortress, and witness the sacred Temple of the Tooth in Kandy. This journey through the Cultural Triangle reveals centuries of Buddhist heritage and royal grandeur.",
    durationDays: 5,
    durationNights: 4,
    priceFromUSD: 599,
    regions: ["Cultural Triangle", "Kandy"],
    interests: ["culture", "history", "temples", "unesco"],
    rating: 4.9,
    reviewCount: 127,
    images: [
      "https://images.unsplash.com/photo-1586613835342-7d5e75e1d77b?w=800",
      "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=800",
      "https://images.unsplash.com/photo-1588598198516-5f89f0e300c6?w=800",
    ],
    heroImage: "https://images.unsplash.com/photo-1586613835342-7d5e75e1d77b?w=1200",
    itineraryDays: [
      {
        day: 1,
        title: "Arrival & Colombo City Tour",
        description:
          "Welcome to Sri Lanka! After airport pickup, enjoy a brief tour of Colombo's highlights before heading to Dambulla.",
        activities: ["Airport pickup", "Colombo city tour", "Transfer to Dambulla"],
        meals: ["dinner"],
        accommodation: "Heritage Hotel, Dambulla",
      },
      {
        day: 2,
        title: "Sigiriya Rock Fortress",
        description:
          "Climb the iconic Sigiriya Rock Fortress, a UNESCO World Heritage site with ancient frescoes and stunning views.",
        activities: ["Sigiriya Rock climb", "Ancient frescoes viewing", "Lion's paw entrance"],
        meals: ["breakfast", "lunch"],
        accommodation: "Heritage Hotel, Dambulla",
      },
      {
        day: 3,
        title: "Polonnaruwa Ancient City",
        description:
          "Explore the medieval capital of Polonnaruwa, home to well-preserved ruins and the famous Gal Vihara Buddha statues.",
        activities: ["Polonnaruwa ruins tour", "Gal Vihara visit", "Royal Palace complex"],
        meals: ["breakfast", "lunch"],
        accommodation: "Heritage Hotel, Dambulla",
      },
      {
        day: 4,
        title: "Dambulla Cave Temple & Kandy",
        description: "Visit the stunning Dambulla Cave Temple before traveling to the hill capital of Kandy.",
        activities: ["Dambulla Cave Temple", "Scenic drive to Kandy", "Temple of the Tooth evening ceremony"],
        meals: ["breakfast", "dinner"],
        accommodation: "Queens Hotel, Kandy",
      },
      {
        day: 5,
        title: "Kandy & Departure",
        description: "Morning at leisure in Kandy before transferring to the airport for departure.",
        activities: ["Kandy Lake walk", "Local market visit", "Airport transfer"],
        meals: ["breakfast"],
      },
    ],
    inclusions: [
      "All accommodations (4 nights)",
      "Private air-conditioned vehicle",
      "Professional English-speaking guide",
      "Entrance fees to all sites",
      "Daily breakfast + selected meals",
      "Airport transfers",
      "Bottled water during tours",
    ],
    exclusions: [
      "International flights",
      "Travel insurance",
      "Personal expenses",
      "Tips and gratuities",
      "Meals not mentioned",
    ],
    highlights: [
      "Climb the ancient Sigiriya Rock Fortress",
      "Explore UNESCO World Heritage sites",
      "Witness the Temple of the Tooth ceremony",
      "Discover medieval ruins of Polonnaruwa",
    ],
    travelStyle: "mid",
    featured: true,
  },
  {
    id: "2",
    slug: "hill-country-scenic-ride",
    title: "Hill Country & Ella Scenic Ride",
    shortDescription: "Tea plantations, misty mountains, and the famous nine-arch bridge.",
    description:
      "Journey through Sri Lanka's breathtaking hill country, where emerald tea plantations cascade down misty mountainsides. Experience the legendary train ride to Ella, visit working tea factories, and discover charming colonial-era towns nestled among the clouds.",
    durationDays: 4,
    durationNights: 3,
    priceFromUSD: 449,
    regions: ["Hill Country", "Ella", "Nuwara Eliya"],
    interests: ["nature", "scenic", "tea", "trains", "photography"],
    rating: 4.8,
    reviewCount: 98,
    images: [
      "https://images.unsplash.com/photo-1566766189268-73acf97f9de7?w=800",
      "https://images.unsplash.com/photo-1588598198516-5f89f0e300c6?w=800",
      "https://images.unsplash.com/photo-1546708770-599a1b9e1d02?w=800",
    ],
    heroImage: "https://images.unsplash.com/photo-1566766189268-73acf97f9de7?w=1200",
    itineraryDays: [
      {
        day: 1,
        title: "Kandy to Nuwara Eliya",
        description: "Scenic drive through tea country, visiting a tea factory along the way.",
        activities: ["Tea factory tour", "Tea tasting", "Nuwara Eliya town walk"],
        meals: ["breakfast", "dinner"],
        accommodation: "Grand Hotel, Nuwara Eliya",
      },
      {
        day: 2,
        title: "Horton Plains & Train to Ella",
        description: "Early morning hike to World's End, then catch the famous scenic train to Ella.",
        activities: ["Horton Plains hike", "World's End viewpoint", "Scenic train journey"],
        meals: ["breakfast", "lunch"],
        accommodation: "98 Acres Resort, Ella",
      },
      {
        day: 3,
        title: "Ella Adventures",
        description: "Explore Ella's famous sites including Nine Arch Bridge and Little Adam's Peak.",
        activities: ["Nine Arch Bridge", "Little Adam's Peak hike", "Ravana Falls"],
        meals: ["breakfast"],
        accommodation: "98 Acres Resort, Ella",
      },
      {
        day: 4,
        title: "Departure",
        description: "Morning at leisure before transfer to your next destination.",
        activities: ["Leisure time", "Transfer"],
        meals: ["breakfast"],
      },
    ],
    inclusions: [
      "All accommodations (3 nights)",
      "Private vehicle with driver",
      "Train tickets (2nd class reserved)",
      "Tea factory entrance",
      "Horton Plains entrance",
      "Daily breakfast",
    ],
    exclusions: ["International flights", "Travel insurance", "Personal expenses", "Tips", "Meals not mentioned"],
    highlights: [
      "Iconic train ride through tea country",
      "Sunrise at World's End",
      "Instagram-famous Nine Arch Bridge",
      "Fresh Ceylon tea tasting",
    ],
    travelStyle: "mid",
    featured: true,
  },
  {
    id: "3",
    slug: "southern-coast-relaxation",
    title: "Southern Coast Relaxation",
    shortDescription: "Beach bliss, whale watching, and colonial charm in Galle.",
    description:
      "Unwind on the pristine beaches of Sri Lanka's southern coast, where golden sands meet turquoise waters. Explore the UNESCO-listed Galle Fort, go whale watching in Mirissa, and experience the laid-back coastal lifestyle.",
    durationDays: 6,
    durationNights: 5,
    priceFromUSD: 799,
    regions: ["South Coast", "Galle", "Mirissa", "Unawatuna"],
    interests: ["beach", "relaxation", "whales", "colonial", "surfing"],
    rating: 4.7,
    reviewCount: 156,
    images: [
      "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    ],
    heroImage: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=1200",
    itineraryDays: [
      {
        day: 1,
        title: "Arrival to Bentota",
        description: "Transfer to Bentota beach resort, evening at leisure.",
        activities: ["Airport transfer", "Beach time", "Welcome dinner"],
        meals: ["dinner"],
        accommodation: "Bentota Beach Hotel",
      },
      {
        day: 2,
        title: "Bentota Water Sports",
        description: "Full day of water activities and relaxation.",
        activities: ["River safari", "Water sports", "Beach relaxation"],
        meals: ["breakfast"],
        accommodation: "Bentota Beach Hotel",
      },
      {
        day: 3,
        title: "Galle Fort Exploration",
        description: "Discover the charming streets of UNESCO-listed Galle Fort.",
        activities: ["Galle Fort walking tour", "Boutique shopping", "Sunset at ramparts"],
        meals: ["breakfast", "lunch"],
        accommodation: "Fort Bazaar, Galle",
      },
      {
        day: 4,
        title: "Mirissa Beach",
        description: "Travel to Mirissa for whale watching and beach time.",
        activities: ["Transfer to Mirissa", "Beach relaxation", "Sunset watching"],
        meals: ["breakfast"],
        accommodation: "Mirissa Hills, Mirissa",
      },
      {
        day: 5,
        title: "Whale Watching",
        description: "Early morning whale watching expedition to spot blue whales and dolphins.",
        activities: ["Whale watching cruise", "Beach relaxation", "Farewell dinner"],
        meals: ["breakfast", "dinner"],
        accommodation: "Mirissa Hills, Mirissa",
      },
      {
        day: 6,
        title: "Departure",
        description: "Transfer to airport for departure.",
        activities: ["Airport transfer"],
        meals: ["breakfast"],
      },
    ],
    inclusions: [
      "Beachfront accommodations (5 nights)",
      "Private air-conditioned vehicle",
      "Whale watching tour",
      "Galle Fort guided tour",
      "Daily breakfast",
      "Airport transfers",
    ],
    exclusions: ["International flights", "Water sports activities", "Travel insurance", "Personal expenses", "Tips"],
    highlights: [
      "Whale watching in Mirissa",
      "UNESCO Galle Fort exploration",
      "Pristine southern beaches",
      "River safari in Bentota",
    ],
    travelStyle: "mid",
    featured: true,
  },
  {
    id: "4",
    slug: "wildlife-safari-adventure",
    title: "Wildlife & Safari Adventure",
    shortDescription: "Encounter leopards, elephants, and exotic birds in their natural habitat.",
    description:
      "Experience the thrill of Sri Lankan wildlife across two of the island's premier national parks. Track elusive leopards in Yala, witness elephant gatherings in Udawalawe, and discover the incredible biodiversity of this tropical paradise.",
    durationDays: 4,
    durationNights: 3,
    priceFromUSD: 549,
    regions: ["Yala", "Udawalawe"],
    interests: ["wildlife", "safari", "nature", "photography", "adventure"],
    rating: 4.9,
    reviewCount: 89,
    images: [
      "https://images.unsplash.com/photo-1549366021-9f761d450615?w=800",
      "https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=800",
      "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800",
    ],
    heroImage: "https://images.unsplash.com/photo-1549366021-9f761d450615?w=1200",
    itineraryDays: [
      {
        day: 1,
        title: "Arrival to Udawalawe",
        description: "Transfer to Udawalawe, visit the Elephant Transit Home.",
        activities: ["Transfer to Udawalawe", "Elephant Transit Home visit", "Evening safari"],
        meals: ["dinner"],
        accommodation: "Grand Udawalawe Safari Resort",
      },
      {
        day: 2,
        title: "Udawalawe Safari & Yala",
        description: "Morning safari in Udawalawe before heading to Yala.",
        activities: ["Morning safari", "Transfer to Yala", "Sunset at lodge"],
        meals: ["breakfast", "lunch", "dinner"],
        accommodation: "Cinnamon Wild Yala",
      },
      {
        day: 3,
        title: "Yala Leopard Safari",
        description: "Full day of safaris in Yala National Park, hunting for leopards.",
        activities: ["Early morning safari", "Afternoon safari", "Wildlife photography"],
        meals: ["breakfast", "lunch", "dinner"],
        accommodation: "Cinnamon Wild Yala",
      },
      {
        day: 4,
        title: "Morning Safari & Departure",
        description: "Final morning safari before transfer to your next destination.",
        activities: ["Sunrise safari", "Transfer"],
        meals: ["breakfast"],
      },
    ],
    inclusions: [
      "Safari lodge accommodations (3 nights)",
      "4x4 safari jeep with tracker",
      "All national park entrance fees",
      "Elephant Transit Home entrance",
      "Full board meals at lodges",
      "Transfers",
    ],
    exclusions: [
      "International flights",
      "Camera/video fees at parks",
      "Travel insurance",
      "Tips for rangers",
      "Personal expenses",
    ],
    highlights: [
      "Track Sri Lankan leopards",
      "Elephant herds at Udawalawe",
      "Expert wildlife trackers",
      "Luxury safari lodges",
    ],
    travelStyle: "mid",
    featured: true,
  },
  {
    id: "5",
    slug: "luxury-honeymoon-escape",
    title: "Luxury Honeymoon Sri Lanka",
    shortDescription: "Romance and luxury across Sri Lanka's most beautiful destinations.",
    description:
      "Celebrate your love story in paradise. This carefully curated honeymoon experience combines Sri Lanka's most romantic settings with world-class luxury. From misty tea estates to golden beaches, every moment is designed for couples seeking an unforgettable escape.",
    durationDays: 7,
    durationNights: 6,
    priceFromUSD: 1899,
    regions: ["Kandy", "Hill Country", "South Coast"],
    interests: ["honeymoon", "luxury", "romance", "spa", "beach"],
    rating: 5.0,
    reviewCount: 42,
    images: [
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
    ],
    heroImage: "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=1200",
    itineraryDays: [
      {
        day: 1,
        title: "Arrival & Kandy",
        description: "VIP airport welcome and transfer to your luxury boutique hotel in Kandy.",
        activities: ["VIP airport pickup", "Champagne welcome", "Private dinner"],
        meals: ["dinner"],
        accommodation: "Kandy House",
      },
      {
        day: 2,
        title: "Kandy Romance",
        description: "Private temple visit and couples spa experience.",
        activities: ["Temple of the Tooth", "Couples spa treatment", "Candlelit dinner"],
        meals: ["breakfast", "dinner"],
        accommodation: "Kandy House",
      },
      {
        day: 3,
        title: "Tea Country Retreat",
        description: "Scenic drive to a stunning tea estate bungalow.",
        activities: ["Private tea tasting", "Estate walk", "Sunset cocktails"],
        meals: ["breakfast", "lunch", "dinner"],
        accommodation: "Ceylon Tea Trails",
      },
      {
        day: 4,
        title: "Tea Trails Bliss",
        description: "A day of relaxation and exploration at the tea trails.",
        activities: ["Tea plucking experience", "Picnic lunch", "In-room dining"],
        meals: ["breakfast", "lunch", "dinner"],
        accommodation: "Ceylon Tea Trails",
      },
      {
        day: 5,
        title: "Southern Paradise",
        description: "Transfer to a beachfront villa on the southern coast.",
        activities: ["Scenic drive", "Beach villa check-in", "Private beach dinner"],
        meals: ["breakfast", "dinner"],
        accommodation: "Amanwella",
      },
      {
        day: 6,
        title: "Beach Bliss",
        description: "Full day of beach relaxation and water activities.",
        activities: ["Beach time", "Sunset catamaran cruise", "Champagne dinner"],
        meals: ["breakfast", "dinner"],
        accommodation: "Amanwella",
      },
      {
        day: 7,
        title: "Farewell",
        description: "Leisurely morning before airport transfer.",
        activities: ["Late checkout", "VIP airport transfer"],
        meals: ["breakfast"],
      },
    ],
    inclusions: [
      "Luxury accommodations (6 nights)",
      "Private chauffeur-driven vehicle",
      "All meals at properties",
      "Couples spa treatments",
      "Private experiences as listed",
      "Champagne & flowers",
      "VIP airport services",
    ],
    exclusions: ["International flights", "Travel insurance", "Personal expenses", "Gratuities"],
    highlights: [
      "World-class luxury properties",
      "Private romantic experiences",
      "Champagne throughout the journey",
      "Couples spa treatments",
    ],
    travelStyle: "luxury",
    featured: true,
  },
  {
    id: "6",
    slug: "complete-sri-lanka-discovery",
    title: "Complete Sri Lanka Discovery",
    shortDescription: "The ultimate journey covering all of Sri Lanka's highlights.",
    description:
      "Experience the best of Sri Lanka in this comprehensive tour. From ancient ruins to pristine beaches, misty mountains to wildlife safaris, this journey covers every facet of this incredible island nation.",
    durationDays: 12,
    durationNights: 11,
    priceFromUSD: 1299,
    regions: ["Cultural Triangle", "Kandy", "Hill Country", "Yala", "South Coast"],
    interests: ["culture", "wildlife", "beach", "nature", "adventure"],
    rating: 4.8,
    reviewCount: 203,
    images: [
      "https://images.unsplash.com/photo-1586613835342-7d5e75e1d77b?w=800",
      "https://images.unsplash.com/photo-1566766189268-73acf97f9de7?w=800",
      "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800",
    ],
    heroImage: "https://images.unsplash.com/photo-1586613835342-7d5e75e1d77b?w=1200",
    itineraryDays: [
      {
        day: 1,
        title: "Arrival",
        description: "Welcome to Sri Lanka",
        activities: ["Airport pickup", "Welcome dinner"],
        meals: ["dinner"],
        accommodation: "Colombo",
      },
      {
        day: 2,
        title: "Cultural Triangle",
        description: "Explore ancient wonders",
        activities: ["Sigiriya Rock"],
        meals: ["breakfast", "lunch"],
        accommodation: "Dambulla",
      },
      {
        day: 3,
        title: "Ancient Cities",
        description: "Polonnaruwa exploration",
        activities: ["Ruins tour"],
        meals: ["breakfast", "lunch"],
        accommodation: "Dambulla",
      },
      {
        day: 4,
        title: "To Kandy",
        description: "Journey to the hill capital",
        activities: ["Temple of Tooth"],
        meals: ["breakfast", "dinner"],
        accommodation: "Kandy",
      },
      {
        day: 5,
        title: "Kandy",
        description: "Cultural experiences",
        activities: ["Gardens", "Dance show"],
        meals: ["breakfast"],
        accommodation: "Kandy",
      },
      {
        day: 6,
        title: "Hill Country",
        description: "Tea plantations",
        activities: ["Tea factory", "Train ride"],
        meals: ["breakfast", "lunch"],
        accommodation: "Ella",
      },
      {
        day: 7,
        title: "Ella",
        description: "Mountain adventures",
        activities: ["Nine Arch Bridge"],
        meals: ["breakfast"],
        accommodation: "Ella",
      },
      {
        day: 8,
        title: "Yala",
        description: "Safari time",
        activities: ["Evening safari"],
        meals: ["breakfast", "dinner"],
        accommodation: "Yala",
      },
      {
        day: 9,
        title: "Safari Day",
        description: "Full day wildlife",
        activities: ["Safaris"],
        meals: ["breakfast", "lunch", "dinner"],
        accommodation: "Yala",
      },
      {
        day: 10,
        title: "Beach Time",
        description: "Southern coast",
        activities: ["Beach relaxation"],
        meals: ["breakfast"],
        accommodation: "Mirissa",
      },
      {
        day: 11,
        title: "Galle & Beach",
        description: "Fort and coast",
        activities: ["Galle Fort", "Whale watching"],
        meals: ["breakfast", "dinner"],
        accommodation: "Galle",
      },
      { day: 12, title: "Departure", description: "Farewell", activities: ["Airport transfer"], meals: ["breakfast"] },
    ],
    inclusions: [
      "All accommodations",
      "Private vehicle",
      "English-speaking guide",
      "Entrance fees",
      "Safari jeep",
      "Daily breakfast",
    ],
    exclusions: ["Flights", "Insurance", "Personal expenses", "Tips"],
    highlights: [
      "All major highlights in one tour",
      "Perfect introduction to Sri Lanka",
      "Mix of culture, nature, and beach",
      "Flexible pace",
    ],
    travelStyle: "mid",
    featured: true,
  },
];

export const destinations: Destination[] = [
  {
    id: "1",
    slug: "sigiriya",
    name: "Sigiriya",
    shortDescription: "The iconic Lion Rock fortress rising from the jungle.",
    description:
      "Sigiriya, the ancient rock fortress, stands as one of Sri Lanka's most iconic landmarks. This UNESCO World Heritage site features a palace complex built atop a massive rock column, ancient frescoes, and mirror walls with centuries-old graffiti.",
    heroImage:
      "https://cdn.bunniktours.com.au/public/posts/images/Asia/2023%20-%20Sri%20Lanka%20-%20Sigiriya%20Rock%20-%20Thomas%20Altschwager%20%283%29-feature.jpg",
    images: [
      "https://images.unsplash.com/photo-1586613835342-7d5e75e1d77b?w=800",
      "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=800",
    ],
    bestTimeToVisit: "January to April",
    tags: ["UNESCO", "History", "Adventure", "Photography"],
    highlights: [
      "Climb Sigiriya Rock Fortress at sunrise",
      "Explore ancient frescoes gallery",
      "Walk through the Water Gardens",
      "Visit the Lion's Paw entrance",
      "Village safari by tuk-tuk",
      "Pidurangala Rock sunset hike",
    ],
    region: "Cultural Triangle",
  },
  {
    id: "2",
    slug: "ella",
    name: "Ella",
    shortDescription: "Misty mountains, tea trails, and the iconic Nine Arch Bridge.",
    description:
      "Ella is a picturesque hill town surrounded by lush tea plantations and misty peaks. Famous for the Instagram-worthy Nine Arch Bridge, scenic train journeys, and breathtaking hikes, Ella offers the perfect blend of adventure and relaxation in the Sri Lankan highlands.",
    heroImage: "https://www.travelwithachila.com/wp-content/uploads/2023/06/Ella-Sri-Lanka.jpg",
    images: ["https://images.unsplash.com/photo-1566766189268-73acf97f9de7?w=800"],
    bestTimeToVisit: "January to March",
    tags: ["Mountains", "Tea", "Scenic", "Hiking"],
    highlights: [
      "Watch trains cross Nine Arch Bridge",
      "Hike Little Adam's Peak at sunrise",
      "Take the scenic train from Kandy",
      "Explore tea plantations",
      "Visit Ravana Falls",
      "Tour local tea estates",
    ],
    region: "Hill Country",
  },
  {
    id: "3",
    slug: "kandy",
    name: "Kandy",
    shortDescription: "Sacred city and home to the Temple of the Tooth.",
    description:
      "The last capital of the Sinhalese kings, Kandy is a UNESCO World Heritage site known for the sacred Temple of the Tooth Relic. Set around a beautiful lake, the city offers rich cultural experiences, traditional dance performances, and botanical gardens.",
    heroImage: "https://www.chamilatours.com/wp-content/uploads/2022/09/Kandy-Temple-of-Tooth-Relic-2.jpg",
    images: ["https://images.unsplash.com/photo-1590123547530-82e28f8c6f46?w=800"],
    bestTimeToVisit: "January to April",
    tags: ["UNESCO", "Culture", "Temples", "Heritage"],
    highlights: [
      "Visit Temple of the Sacred Tooth Relic",
      "Stroll around Kandy Lake",
      "Explore Royal Botanical Gardens",
      "Watch traditional Kandyan dance show",
      "Shop at the Central Market",
      "Take a scenic train to Ella",
    ],
    region: "Central Province",
  },
  {
    id: "4",
    slug: "galle",
    name: "Galle",
    shortDescription: "Colonial charm within ancient fort walls.",
    description:
      "Galle Fort is a UNESCO World Heritage site featuring Dutch colonial architecture, boutique shops, art galleries, and charming cafes within its 400-year-old walls. Watch the sunset from the ramparts for an unforgettable experience.",
    heroImage: "https://as2.ftcdn.net/v2/jpg/02/42/22/05/1000_F_242220505_HZ7u0BxFMXBs8vSW7f3qN2l3POhPK73R.jpg",
    images: ["https://images.unsplash.com/photo-1588416936097-41850ab3d86d?w=800"],
    bestTimeToVisit: "November to April",
    tags: ["UNESCO", "Colonial", "Beach", "Architecture"],
    highlights: [
      "Walk the historic Fort ramparts at sunset",
      "Explore boutique shops and galleries",
      "Visit the Dutch Reformed Church",
      "Climb the iconic lighthouse",
      "Enjoy café hopping in the Fort",
      "Discover the Maritime Museum",
    ],
    region: "South Coast",
  },
  {
    id: "5",
    slug: "unawatuna",
    name: "Unawatuna",
    shortDescription: "Tropical beach paradise with crystal-clear waters.",
    description:
      "Unawatuna is one of Sri Lanka's most popular beaches, known for its crescent-shaped bay, calm turquoise waters, and vibrant coral reefs. This laid-back beach town offers excellent snorkeling, diving, and a relaxed tropical atmosphere.",
    heroImage: "https://www.srilankanexpeditions.co.uk/images/main_slider/unawatuna-beach/01.jpg",
    images: ["https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?w=800"],
    bestTimeToVisit: "November to April",
    tags: ["Beach", "Snorkeling", "Diving", "Relaxation"],
    highlights: [
      "Snorkel the coral reef",
      "Scuba dive at Goda Gala",
      "Visit the Japanese Peace Pagoda",
      "Kayak in the calm bay",
      "Watch sea turtles at the hatchery",
      "Enjoy beachfront dining at sunset",
    ],
    region: "South Coast",
  },
  {
    id: "6",
    slug: "mirissa",
    name: "Mirissa",
    shortDescription: "Paradise beach and whale watching capital.",
    description:
      "Mirissa is a tropical beach paradise known for whale watching, surfing, and stunning sunsets. This laid-back coastal town offers palm-fringed beaches, fresh seafood, and the chance to spot blue whales just offshore.",
    heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800"],
    bestTimeToVisit: "November to April",
    tags: ["Beach", "Whales", "Surfing", "Nightlife"],
    highlights: [
      "Blue whale watching boat tours",
      "Climb Coconut Tree Hill at sunset",
      "Surf the morning waves",
      "Explore Secret Beach",
      "Feast on fresh seafood BBQ",
      "Night out at beach bars",
    ],
    region: "South Coast",
  },
  {
    id: "7",
    slug: "yala",
    name: "Yala National Park",
    shortDescription: "Highest leopard density in the world.",
    description:
      "Yala National Park is Sri Lanka's most famous wildlife reserve, boasting the highest density of leopards in the world. The park also hosts elephants, sloth bears, crocodiles, and diverse birdlife across its varied ecosystems.",
    heroImage: "https://www.andbeyond.com/wp-content/uploads/sites/5/sri-lanka-leopard-asian.jpg",
    images: ["https://images.unsplash.com/photo-1549366021-9f761d450615?w=800"],
    bestTimeToVisit: "February to July",
    tags: ["Wildlife", "Safari", "Leopards", "Nature"],
    highlights: [
      "Track elusive leopards on safari",
      "Spot wild elephant herds",
      "Bird watching with 200+ species",
      "See sloth bears in the wild",
      "Visit ancient Sithulpawwa Temple",
      "Photograph stunning landscapes",
    ],
    region: "South East",
  },
  {
    id: "8",
    slug: "nuwara-eliya",
    name: "Nuwara Eliya",
    shortDescription: "Little England in the clouds.",
    description:
      'Known as "Little England," Nuwara Eliya is a charming hill station with colonial-era bungalows, manicured gardens, and cool misty weather. Surrounded by tea plantations, it offers a unique glimpse of Sri Lanka\'s colonial heritage.',
    heroImage: "https://srilankatourisminfo.com/wp-content/uploads/2018/08/image-result-for-nuwara-eliya-by-train-2.jpeg",
    images: ["https://images.unsplash.com/photo-1546708770-599a1b9e1d02?w=800"],
    bestTimeToVisit: "February to April",
    tags: ["Tea", "Colonial", "Gardens", "Cool Climate"],
    highlights: [
      "Tour working tea factories",
      "Visit Victoria Park gardens",
      "Boat on Gregory Lake",
      "Hike to Horton Plains & World's End",
      "Pick fresh strawberries at farms",
      "Explore colonial-era bungalows",
    ],
    region: "Hill Country",
  },
  {
    id: "9",
    slug: "colombo",
    name: "Colombo",
    shortDescription: "Vibrant capital blending old and new.",
    description:
      "Sri Lanka's bustling capital is a dynamic city where colonial buildings stand alongside modern skyscrapers. Explore historic neighborhoods, visit temples and mosques, enjoy diverse cuisine, and experience the country's contemporary culture.",
    heroImage: "https://cdn.britannica.com/61/192661-050-997DE572/Colombo-Sri-Lanka.jpg",
    images: ["https://images.unsplash.com/photo-1578005343857-82e0f50e8f36?w=800"],
    bestTimeToVisit: "Year-round",
    tags: ["City", "Shopping", "Food", "Culture"],
    highlights: [
      "Sunset at Galle Face Green",
      "Explore chaotic Pettah Market",
      "Visit Gangaramaya Temple",
      "Fine dining experiences",
      "Shopping at Odel & One Galle Face",
      "Street food tour",
    ],
    region: "Western Province",
  },
  {
    id: "10",
    slug: "anuradhapura",
    name: "Anuradhapura",
    shortDescription: "Ancient sacred city and Buddhist pilgrimage site.",
    description:
      "Anuradhapura is one of the ancient capitals of Sri Lanka and a sacred Buddhist pilgrimage site. This UNESCO World Heritage city features massive stupas, ancient monasteries, and the sacred Sri Maha Bodhi tree, believed to be the oldest historically documented tree in the world.",
    heroImage: "https://chaaliya.com/wp-content/uploads/2017/11/Anuradhapura-01-800x500.png",
    images: ["https://images.unsplash.com/photo-1625736300986-9b3c29f7d0e3?w=800"],
    bestTimeToVisit: "February to September",
    tags: ["UNESCO", "Buddhism", "History", "Sacred"],
    highlights: [
      "Pay respects at Sri Maha Bodhi tree",
      "Marvel at Ruwanwelisaya Stupa",
      "Explore Jetavanaramaya ruins",
      "Cycle through the ancient city",
      "Visit Isurumuniya Temple",
      "Discover Abhayagiri Monastery",
    ],
    region: "North Central Province",
  },
  {
    id: "11",
    slug: "trincomalee",
    name: "Trincomalee",
    shortDescription: "East coast gem with pristine beaches and temples.",
    description:
      "Trincomalee boasts some of Sri Lanka's most pristine beaches and one of the world's finest natural harbors. This historic port city offers stunning Hindu temples perched on clifftops, whale watching, and crystal-clear waters perfect for diving.",
    heroImage: "https://www.lanka-excursions-holidays.com/uploads/4/0/2/1/40216937/trincomalee-dscf6230-1200_orig.jpg",
    images: ["https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800"],
    bestTimeToVisit: "April to September",
    tags: ["Beach", "Temples", "Diving", "Whales"],
    highlights: [
      "Visit Koneswaram Temple on the cliff",
      "Swim at Nilaveli Beach",
      "Dive at Pigeon Island",
      "Go whale & dolphin watching",
      "Explore Fort Frederick",
      "Soak in Kanniya Hot Springs",
    ],
    region: "East Coast",
  },
  {
    id: "12",
    slug: "jaffna",
    name: "Jaffna",
    shortDescription: "Cultural capital of the Tamil North.",
    description:
      "Jaffna, the cultural capital of Sri Lanka's Tamil population, offers a unique glimpse into the country's Hindu heritage. With its ancient temples, distinctive cuisine, and resilient spirit, Jaffna provides an authentic cultural experience off the beaten path.",
    heroImage: "https://www.yogawinetravel.com/wp-content/uploads/2024/11/Drone-photo-of-Jaffna-Fort-in-Sri-Lanka_featured.jpg",
    images: ["https://images.unsplash.com/photo-1590123547530-82e28f8c6f46?w=800"],
    bestTimeToVisit: "January to September",
    tags: ["Culture", "Temples", "Heritage", "Food"],
    highlights: [
      "Explore Nallur Kandaswamy Temple",
      "Visit Jaffna Fort",
      "Island hop to Nainativu",
      "Taste authentic Jaffna cuisine",
      "Discover the Jaffna Library",
      "Cycle through palm-lined villages",
    ],
    region: "Northern Province",
  },
  {
    id: "13",
    slug: "bentota",
    name: "Bentota",
    shortDescription: "Premier beach resort destination with river adventures.",
    description:
      "Bentota is Sri Lanka's premier beach resort destination, where golden sands meet the calm waters of both ocean and river. This dual waterfront paradise offers water sports, luxury resorts, and the famous Bentota River mangrove ecosystem.",
    heroImage: "https://www.suryalanka.com/wp-content/uploads/2020/07/bentota-beach.jpg",
    images: ["https://images.unsplash.com/photo-1540202404-a2f29016b523?w=800"],
    bestTimeToVisit: "November to April",
    tags: ["Beach", "Water Sports", "Luxury", "River"],
    highlights: [
      "Jet-ski on the Bentota River",
      "Safari through mangrove forests",
      "Visit Brief Garden",
      "Relax at luxury beach resorts",
      "Try kite surfing",
      "Explore the Turtle Hatchery",
    ],
    region: "South Coast",
  },
  {
    id: "14",
    slug: "udawalawe",
    name: "Udawalawe National Park",
    shortDescription: "Best place to see wild elephants in Sri Lanka.",
    description:
      "Udawalawe National Park is renowned for its large elephant population, offering almost guaranteed sightings of these majestic creatures. The park also features diverse wildlife, beautiful landscapes around the reservoir, and the Elephant Transit Home sanctuary.",
    heroImage: "https://www.serendibtrail.com/content/images/size/w1200/2024/10/udawalawe-national-park.webp",
    images: ["https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=800"],
    bestTimeToVisit: "Year-round",
    tags: ["Wildlife", "Elephants", "Safari", "Nature"],
    highlights: [
      "Morning safari for elephant herds",
      "Visit Elephant Transit Home",
      "Spot water buffalo and crocodiles",
      "Bird watching at the reservoir",
      "Photograph sambar deer",
      "Sunset safari game drive",
    ],
    region: "Sabaragamuwa Province",
  },
];

export const services: Service[] = [
  {
    id: "1",
    title: "Private Transportation",
    description: "Travel in comfort with our fleet of modern, air-conditioned vehicles and experienced drivers.",
    icon: "car",
    features: ["Air-conditioned vehicles", "Professional drivers", "Flexible schedules", "Airport transfers"],
  },
  {
    id: "2",
    title: "Expert Guides",
    description: "Our certified guides bring history and culture to life with their deep knowledge and passion.",
    icon: "user",
    features: ["Licensed guides", "Multi-lingual", "Cultural insights", "Personalized tours"],
  },
  {
    id: "3",
    title: "Hotel Bookings",
    description: "Handpicked accommodations ranging from boutique hotels to luxury resorts.",
    icon: "building",
    features: ["Vetted properties", "Best rates", "All categories", "Special requests"],
  },
  {
    id: "4",
    title: "Airport Services",
    description: "Seamless airport pickups and drop-offs with meet-and-greet service.",
    icon: "plane",
    features: ["Meet & greet", "Flight tracking", "24/7 service", "VIP options"],
  },
  {
    id: "5",
    title: "Visa Assistance",
    description: "We help navigate the visa process for a hassle-free entry to Sri Lanka.",
    icon: "file-text",
    features: ["ETA applications", "Extension help", "Documentation", "Expert guidance"],
  },
  {
    id: "6",
    title: "Safari Tours",
    description: "Experience wildlife up close with our expert-led safari adventures.",
    icon: "binoculars",
    features: ["4x4 jeeps", "Expert trackers", "Multiple parks", "Photography focus"],
  },
  {
    id: "7",
    title: "Whale Watching",
    description: "Encounter blue whales and dolphins on our responsible whale watching tours.",
    icon: "anchor",
    features: ["Experienced captains", "Safety first", "Season expertise", "Small groups"],
  },
  {
    id: "8",
    title: "Train Reservations",
    description: "Secure seats on Sri Lanka's famous scenic train journeys.",
    icon: "train",
    features: ["Reserved seats", "Scenic routes", "First & second class", "Observation cars"],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Sarah Mitchell",
    country: "United Kingdom",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
    rating: 5,
    text: "LS Tours made our honeymoon absolutely magical! From the luxury accommodations to our wonderful driver Nimal, every detail was perfect. The surprise champagne dinner on the beach was unforgettable.",
    packageTitle: "Luxury Honeymoon Sri Lanka",
    date: "2024-01",
  },
  {
    id: "2",
    name: "Hans Weber",
    country: "Germany",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
    rating: 5,
    text: "The Cultural Triangle tour exceeded all expectations. Our guide's knowledge of history was impressive, and climbing Sigiriya at sunrise was a bucket-list moment. Highly recommend!",
    packageTitle: "Cultural Triangle Explorer",
    date: "2024-02",
  },
  {
    id: "3",
    name: "Emma Chen",
    country: "Australia",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100",
    rating: 5,
    text: "Saw 3 leopards in Yala and countless elephants in Udawalawe! The safari lodges were incredible and our tracker knew exactly where to find wildlife. Best safari experience ever.",
    packageTitle: "Wildlife & Safari Adventure",
    date: "2024-01",
  },
  {
    id: "4",
    name: "Pierre Dubois",
    country: "France",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100",
    rating: 4,
    text: "The train journey through tea country was spectacular. Ella is now one of my favorite places on Earth. LS Tours arranged everything seamlessly.",
    packageTitle: "Hill Country & Ella Scenic Ride",
    date: "2023-12",
  },
  {
    id: "5",
    name: "Maria Santos",
    country: "Brazil",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100",
    rating: 5,
    text: "We watched blue whales in Mirissa and explored Galle Fort - such diverse experiences! The beaches were pristine and accommodation was top-notch.",
    packageTitle: "Southern Coast Relaxation",
    date: "2024-02",
  },
];

export const interestOptions = [
  { value: "culture", label: "Culture & History" },
  { value: "wildlife", label: "Wildlife & Safari" },
  { value: "beach", label: "Beach & Relaxation" },
  { value: "adventure", label: "Adventure" },
  { value: "honeymoon", label: "Honeymoon" },
  { value: "nature", label: "Nature & Scenic" },
  { value: "photography", label: "Photography" },
  { value: "food", label: "Food & Culinary" },
];

export const regionOptions = [
  { value: "cultural-triangle", label: "Cultural Triangle" },
  { value: "hill-country", label: "Hill Country" },
  { value: "south-coast", label: "South Coast" },
  { value: "east-coast", label: "East Coast" },
  { value: "wildlife", label: "Wildlife Regions" },
];

export const durationOptions = [
  { value: "1-3", label: "1-3 Days" },
  { value: "4-6", label: "4-6 Days" },
  { value: "7-10", label: "7-10 Days" },
  { value: "10+", label: "10+ Days" },
];

export const travelStyleOptions = [
  { value: "budget", label: "Budget" },
  { value: "mid", label: "Mid-Range" },
  { value: "luxury", label: "Luxury" },
];
